input {
  tcp {
    port => 5000
    codec => json
  }
  udp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "java-log" {
    mutate {
      add_field => { "[@metadata][index_name]" => "retailr-logs-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index_name]}"
    manage_template => true
    template => "/usr/share/logstash/templates/ecs-log-template.json"
    template_name => "ecs-log-template"
  }
  stdout {
    codec => json
  }
}
