// Re-export all API types from the canonical types module for backward compat
export type {
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  AuthUserDTO,
  UserDTO,
  ProductDTO,
  CreateProductRequest,
  UpdateProductRequest,
  CategoryDTO,
  CreateCategoryRequest,
  UpdateCategoryRequest,
  SupplierDTO,
  CreateSupplierRequest,
  UpdateSupplierRequest,
  StockItemDTO,
  StockMovementDTO,
  StockMovementType,
  CreateStockMovementRequest,
  LowStockAlertDTO,
  WarehouseDTO,
  OrderDTO,
  OrderLineDTO,
  OrderStatus,
  CreateOrderRequest,
  CreateOrderLineRequest,
  UpdateOrderStatusRequest,
  CustomerDTO,
  CreateCustomerRequest,
  UpdateCustomerRequest,
  PageResponse,
  PageRequest,
  ApiErrorResponse,
} from '@/types/api';
